# World Development Indicators

Load the project-local Excel workbook and take a first look at the available data.

In [2]:
from pathlib import Path

import pandas as pd

In [3]:
workbook_path = Path("data/raw/P_WDI_40C_5I_25T.xlsx")

if not workbook_path.exists():
    raise FileNotFoundError("Could not find workbook")

sheets = pd.read_excel(workbook_path, sheet_name=None)
data = sheets["Data"]
metadata = sheets["Series - Metadata"]

In [4]:
sheet_summary = pd.DataFrame(
    [
        {"sheet": name, "data_rows_excluding_header": frame.shape[0], "columns": frame.shape[1]}
        for name, frame in sheets.items()
    ]
)

sheet_summary

               sheet  data_rows_excluding_header  columns
0               Data                         200       29
1  Series - Metadata                           5       15

In [5]:
print("Sheet names:", list(sheets))
print("Data shape, excluding header row:", data.shape)
print("Metadata shape, excluding header row:", metadata.shape)
print("Data columns:")
print(data.columns.to_list())
print("Metadata columns:")
print(metadata.columns.to_list())

Sheet names: ['Data', 'Series - Metadata']
Data shape, excluding header row: (200, 29)
Metadata shape, excluding header row: (5, 15)
Data columns:
['Country Name', 'Country Code', 'Series Name', 'Series Code', '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]']
Metadata columns:
['Code', 'License Type', 'Indicator Name', 'Long definition', 'Source', 'Topic', 'Dataset', 'Unit of measure', 'Periodicity', 'Reference period', 'Aggregation method', 'Statistical concept and methodology', 'Development relevance', 'Limitations and exceptions', 'License URL']

In [6]:
data.head()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Armenia,ARM,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,4589.00825,5044.116478,5731.353466,6569.260234,7299.400019,8362.90084,...,13112.76009,13192.994073,14243.8749,15037.045242,16215.360797,15052.935979,15921.705282,17886.178388,19402.751092,20078.784898
1,Armenia,ARM,Carbon dioxide (CO2) emissions excluding LULUC...,EN.GHG.CO2.PC.CE.AR5,1.108224,1.131266,0.969248,1.090589,1.187778,1.418351,...,1.869533,1.796244,1.909512,2.004581,2.168675,2.334797,2.519461,2.618281,2.52967,2.470282
2,Armenia,ARM,Energy use (kg of oil equivalent per capita),EG.USE.PCAP.KG.OE,625.503227,624.555471,586.440648,622.582881,661.92968,798.544181,...,1084.520629,1043.097972,1105.96697,1072.336825,1163.092847,1233.304559,1271.528056,1347.590557,1300.305327,..
3,Armenia,ARM,Urban population (% of total population),SP.URB.TOTL.IN.ZS,64.959238,64.822812,64.739621,64.666354,64.597263,64.533421,...,64.492962,64.592875,64.712495,64.850283,65.004703,65.174217,65.357288,65.562446,65.695688,65.811367
4,Armenia,ARM,Energy intensity level of primary energy (MJ/$...,EG.EGY.PRIM.PP.KD,6.9,6.28,5.11,4.73,4.53,4.76,...,4.12,3.93,3.86,3.51,3.52,4.01,3.91,..,..,..

In [7]:
metadata.head()

,Code,License Type,Indicator Name,Long definition,Source,Topic,Dataset,Unit of measure,Periodicity,Reference period,Aggregation method,Statistical concept and methodology,Development relevance,Limitations and exceptions,License URL
0,NY.GDP.PCAP.PP.KD,CC BY-4.0,"GDP per capita, PPP (constant 2021 internation...",This indicator provides values for gross domes...,"International Comparison Program (ICP), World ...",Economic Policy & Debt: Purchasing power parity,WB_WDI,Constant 2021 international $,Annual,1990-2024,Weighted average,Methodology: The International Comparison Prog...,PPPs are used to convert national accounts dat...,NaN,https://datacatalog.worldbank.org/public-licen...
1,EN.GHG.CO2.PC.CE.AR5,CC BY-4.0,Carbon dioxide (CO2) emissions excluding LULUC...,Total annual emissions of carbon dioxide (CO2)...,EDGAR (Emissions Database for Global Atmospher...,Environment: Emissions,WB_WDI,t CO2e/capita,Annual,1970-2024,Weighted average using population as weights,Methodology: EDGAR compiles data from multiple...,Anthropogenic (human-caused) emissions of glob...,Global GHG emissions are currently not directl...,https://datacatalog.worldbank.org/public-licen...
2,EG.USE.PCAP.KG.OE,CC BY-4.0,Energy use (kg of oil equivalent per capita),Energy use refers to use of primary energy bef...,"IEA Energy Statistics Data Browser, Internatio...",Environment: Energy production & use,WB_WDI,kg of oil equivalent per capita,Annual,1990-2024,Weighted average,Methodology: Total energy use refers to the us...,In developing economies growth in energy use i...,The IEA makes these estimates in consultation ...,https://datacatalog.worldbank.org/public-licen...
3,SP.URB.TOTL.IN.ZS,CC BY-4.0,Urban population (% of total population),Urban population refers to people living in ur...,"World Urbanization Prospects, United Nations (...",Environment: Density & urbanization,WB_WDI,Percentage,Annual,1960-2025,Weighted average,Methodology: Percentages urban are the numbers...,Explosive growth of cities globally signifies ...,Aggregation of urban and rural population may ...,https://datacatalog.worldbank.org/public-licen...
4,EG.EGY.PRIM.PP.KD,CC BY-4.0,Energy intensity level of primary energy (MJ/$...,Energy intensity level of primary energy is th...,"Tracking SDG 7: The Energy Progress Report, In...",Environment: Energy production & use,WB_WDI,MJ per 2021 USD PPP GDP,Annual,2000-2022,Weighted average,Methodology: This indicator is obtained by div...,NaN,Energy intensity level is only an imperfect pr...,https://datacatalog.worldbank.org/public-licen...

In [8]:
year_columns = [column for column in data.columns if "[YR" in column]

starter_overview = {
    "countries": sorted(data["Country Name"].dropna().unique().tolist()),
    "indicators": sorted(data["Series Name"].dropna().unique().tolist()),
    "year_columns": year_columns,
}

starter_overview

{'countries': ['Albania',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Moldova',
  'Montenegro',
  'Netherlands',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russian Federation',
  'Serbia',
  'Slovak Republic',
  'Slovenia',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom'],
 'indicators': ['Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)',
  'Energy intensity level of primary energy (MJ/$2021 PPP GDP)',
  'Energy use (kg of oil equivalent per capita)',
  'GDP per capita, PPP (constant 2021 international $)',
  'Urban population (% of total population)'],
 'year_columns': ['2000 [YR2000]',
  '2001 [YR2001]',
  '2002 [YR2002]',
  '2003 [YR2003]',
  '2004 [YR2004]',
  '2005 [YR2005]',
  '2006 [YR2006]',
  '2007 [YR2007]',
  '2008 [YR2008]',
  '2009 [YR2009]',
  '2010 [YR2010]',
  '2011 [YR2011]',
  '2012 [YR2012]',
  '2013 [YR2013]',
  '2014 [YR2014]',
  '2015 [YR2015]',
  '2016 [YR2016]',
  '2017 [YR2017]',
  '2018 [YR2018]',
  '2019 [YR2019]',
  '2020 [YR2020]',
  '2021 [YR2021]',
  '2022 [YR2022]',
  '2023 [YR2023]',
  '2024 [YR2024]']}